### PR TITLE
Rust support

### PR DESCRIPTION
**Pull request by hollinwilkins**
Hey @josephDunne, I wanted to help get this PR ready for merging into the google codebase. As a start, I fixed all of the merge conflicts with master. Next up, I need to make sure all of the codegen is still working as expected. Would it be possible for us to generate a TODO list that we can work down before Rust support is ready?

Thank you!
- Hollin

### CODE REVIEW

**Comment by josephDunne** [comment]
Hi and thanks for the help! I will definitely go through the project tonight and create issues that need to be resolved before we can merge into the google code base

**Comment by josephDunne** [comment]
Here is a starter:

* Rust 1.15 introduces custom derive into stable rust - we should use that to derive flatbuffers builders from structs and enums. This is better than the macro system i was using. It will also reduce the amount of c++ code generation we need to maintain.
* Update flatc code generation  
* Write more tests. Original feedback was that we need a fuzz test or at least test parity with the go implementation
* I would like to redo the code in the iter.rs module
* Implement more of the standard rust traits like `ToOwned` `Hash` etc where appropriate

optional stuff:
* Flexbuffers
* gRPC (perhaps best done in a separate crate) 
* I see some code in the merge discussing stores not sure if this is a Go specific thing

I will take some more time and create tickets. @hollinwilkins can you add to the above?

**Comment by hollinwilkins** [comment]
@josephDunne I'd be happy to file these issues and start working on them. Just enable issues in this repo and I'll start making them.

https://softwareengineering.stackexchange.com/questions/179468/forking-a-repo-on-github-but-allowing-new-issues-on-the-fork

**Comment by hollinwilkins** [comment]
@josephDunne Not sure if I have anything to add yet, I need to work on a few of these issues first then I will be more helpful. Let me know when you get the issues setup and we can start working through them.

**Pull request merged**
